let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "1 Month Subscription",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "ioytrhndcv",
    name: "3 Months Subscription",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "wuefbncxbsn",
    name: "6 Months Subscription",
    price: 240,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "thyfhcbcv",
    name: "12 Months Subscription",
    price: 360,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Embroidery Hoodie",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Logo Bottle",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/img1.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Logo Shirt",
    price: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Logo Hat",
    price: 15,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "denim pants",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "basic cap",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "leather boots",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
];
