let shopItemsData = [
  {
    id: "one_month",
    name: "1 Month Subscription",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "three_months",
    name: "3 Months Subscription",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "six_months",
    name: "6 Months Subscription",
    price: 240,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "twelve_months",
    name: "12 Months Subscription",
    price: 360,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "embroidery_hoodie",
    name: "Embroidery Hoodie",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "logo_bottle",
    name: "Logo Bottle",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/img1.jpg",
  },
  {
    id: "logo_shirt",
    name: "Logo Shirt",
    price: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "logo_hat",
    name: "Logo Hat",
    price: 15,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "other_item_1",
    name: "fix",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "other_item_2",
    name: "fix",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "other_item_3",
    name: "fix",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
  {
    id: "other_item_4",
    name: "fix",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo.png",
  },
];