let shopItemsData = [
  {
    id: "one_month",
    name: "1 Month Subscription",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/1_month.png",
  },
  {
    id: "three_months",
    name: "3 Months Subscription",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/3_months.png",
  },
  {
    id: "six_months",
    name: "6 Months Subscription",
    price: 240,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/6_months.png",
  },
  {
    id: "twelve_months",
    name: "12 Months Subscription",
    price: 360,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/12_months.png",
  },
  {
    id: "embroidery_hoodie",
    name: "Embroidery Hoodie",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/hoodie.png",
  },
  {
    id: "logo_bottle",
    name: "Logo Bottle",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo_bottle.png",
  },
  {
    id: "logo_tshirt",
    name: "Logo T-Shirt",
    price: 20,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/t_shirt.png",
  },
  {
    id: "limited_edition_tshirt",
    name: "Limited Edition T-Shirt",
    price: 50,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/t_shirt_v2.png",
  },
  {
    id: "logo_hat",
    name: "Logo Hat",
    price: 10,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo_hat.png",
  },
  {
    id: "logo_shorts",
    name: "Logo Shorts",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/shorts.png",
  },
  {
    id: "logo_hoodie",
    name: "Logo Hoodie",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/logo_hoodie.png",
  },
  {
    id: "leg_warmers",
    name: "Leg Warmers",
    price: 60,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../.utils/images/products/leg_warmers.png",
  },
];